// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH89RE8iw9z7M5dliaYGjbqnY4JKkf3fY',
    appId: '1:309417295021:web:154ebd23d78573c1019a24',
    messagingSenderId: '309417295021',
    projectId: 'riskassessmentnew',
    authDomain: 'riskassessmentnew.firebaseapp.com',
    storageBucket: 'riskassessmentnew.firebasestorage.app',
    measurementId: 'G-1LHLEXFM8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJxTvYHMnf5tcDX3vbpxM1zrr-kRd2vE',
    appId: '1:309417295021:android:8feb53a679d0e68f019a24',
    messagingSenderId: '309417295021',
    projectId: 'riskassessmentnew',
    storageBucket: 'riskassessmentnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8UQaoqcZfy5PQNlmrhqMhGyCRxdue34',
    appId: '1:309417295021:ios:252d899e7b0546ee019a24',
    messagingSenderId: '309417295021',
    projectId: 'riskassessmentnew',
    storageBucket: 'riskassessmentnew.firebasestorage.app',
    iosBundleId: 'com.example.dentalNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8UQaoqcZfy5PQNlmrhqMhGyCRxdue34',
    appId: '1:309417295021:ios:252d899e7b0546ee019a24',
    messagingSenderId: '309417295021',
    projectId: 'riskassessmentnew',
    storageBucket: 'riskassessmentnew.firebasestorage.app',
    iosBundleId: 'com.example.dentalNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH89RE8iw9z7M5dliaYGjbqnY4JKkf3fY',
    appId: '1:309417295021:web:5f37f2c44d7abef0019a24',
    messagingSenderId: '309417295021',
    projectId: 'riskassessmentnew',
    authDomain: 'riskassessmentnew.firebaseapp.com',
    storageBucket: 'riskassessmentnew.firebasestorage.app',
    measurementId: 'G-E9VQ4D4P92',
  );
}
